
export enum Role {
  FRONT_DESK = '理想IT人员/前台支撑人员',
  CUSTOMER_RESPONSE = '客响班',
  CORE_NET = '核心网专业班',
  NET_OPT = '网优专业班',
  TRANS = '传输专业班',
  CORP = '集客专业班',
}

export enum Urgency {
  HIGH = '高',
  MEDIUM = '中',
  LOW = '低',
}

export enum TicketStatus {
  PENDING = '待处理', // 待处理
  IN_PROGRESS = '处理中', // 处理中
  RESOLVED = '已处理', // 已处理
}

export enum WorkflowStage {
  CREATED = '已创建',
  DISPATCHED = '已分派诊断',
  DIAGNOSED = '诊断已回复',
  ANALYZED = 'AI已分析',
  FEEDBACK_PROVIDED = '待归档确认', // New stage: Feedback provided to front desk
  ARCHIVED = '已归档',
}

export interface Diagnosis {
  specialistRole: Role;
  specialistName: string;
  content: string;
  timestamp: string;
}

export interface Ticket {
  id: string;
  title: string;
  description: string;
  urgency: Urgency;
  status: TicketStatus;
  stage: WorkflowStage;
  creator: string;
  createdAt: string;
  resolvedAt?: string; // Timestamp when the ticket was resolved
  assignedTo: Role[]; // Current active assignees
  diagnoses: Diagnosis[];
  aiAnalysis?: string; // The final report generated by AI
}

// New Interface for Manually Uploaded Cases
export interface KnowledgeCase {
  id: string;
  title: string;
  description: string; // Fault description
  solution: string; // Manual solution or analysis
  tags: string[];
  uploader: string;
  createdAt: string;
}

export interface User {
  username: string;
  name: string;
  role: Role;
}
